// @generated by scripts/generate-rust-personality-catalog.mjs
// Source of truth: packages/personality-core/src/personalityCatalog.ts

use std::collections::HashMap;

use crate::engine::types::{BehaviorAxis, TraitKey, TraitVector};

pub fn personality_position(id: &str) -> TraitVector {
    let mut map: HashMap<TraitKey, f64> = HashMap::new();
    match id {
        "playful" => {
            map.insert(TraitKey::Vitality, 90.0);
            map.insert(TraitKey::Sociality, 60.0);
            map.insert(TraitKey::Order, 20.0);
            map.insert(TraitKey::Appetite, 40.0);
            map.insert(TraitKey::Caution, 20.0);
            map.insert(TraitKey::Curiosity, 60.0);
        }
        "drowsy" => {
            map.insert(TraitKey::Vitality, 10.0);
            map.insert(TraitKey::Sociality, 40.0);
            map.insert(TraitKey::Order, 55.0);
            map.insert(TraitKey::Appetite, 35.0);
            map.insert(TraitKey::Caution, 40.0);
            map.insert(TraitKey::Curiosity, 15.0);
        }
        "foodie" => {
            map.insert(TraitKey::Vitality, 55.0);
            map.insert(TraitKey::Sociality, 50.0);
            map.insert(TraitKey::Order, 50.0);
            map.insert(TraitKey::Appetite, 95.0);
            map.insert(TraitKey::Caution, 30.0);
            map.insert(TraitKey::Curiosity, 45.0);
        }
        "bold" => {
            map.insert(TraitKey::Vitality, 80.0);
            map.insert(TraitKey::Sociality, 40.0);
            map.insert(TraitKey::Order, 35.0);
            map.insert(TraitKey::Appetite, 45.0);
            map.insert(TraitKey::Caution, 5.0);
            map.insert(TraitKey::Curiosity, 55.0);
        }
        "zen" => {
            map.insert(TraitKey::Vitality, 30.0);
            map.insert(TraitKey::Sociality, 75.0);
            map.insert(TraitKey::Order, 85.0);
            map.insert(TraitKey::Appetite, 30.0);
            map.insert(TraitKey::Caution, 25.0);
            map.insert(TraitKey::Curiosity, 45.0);
        }
        "anxious" => {
            map.insert(TraitKey::Vitality, 60.0);
            map.insert(TraitKey::Sociality, 50.0);
            map.insert(TraitKey::Order, 40.0);
            map.insert(TraitKey::Appetite, 55.0);
            map.insert(TraitKey::Caution, 90.0);
            map.insert(TraitKey::Curiosity, 50.0);
        }
        "feral" => {
            map.insert(TraitKey::Vitality, 75.0);
            map.insert(TraitKey::Sociality, 10.0);
            map.insert(TraitKey::Order, 15.0);
            map.insert(TraitKey::Appetite, 60.0);
            map.insert(TraitKey::Caution, 15.0);
            map.insert(TraitKey::Curiosity, 55.0);
        }
        "sage" => {
            map.insert(TraitKey::Vitality, 35.0);
            map.insert(TraitKey::Sociality, 65.0);
            map.insert(TraitKey::Order, 70.0);
            map.insert(TraitKey::Appetite, 40.0);
            map.insert(TraitKey::Caution, 45.0);
            map.insert(TraitKey::Curiosity, 90.0);
        }
        "pristine" => {
            map.insert(TraitKey::Vitality, 50.0);
            map.insert(TraitKey::Sociality, 55.0);
            map.insert(TraitKey::Order, 80.0);
            map.insert(TraitKey::Appetite, 40.0);
            map.insert(TraitKey::Caution, 65.0);
            map.insert(TraitKey::Curiosity, 40.0);
        }
        "empath" => {
            map.insert(TraitKey::Vitality, 45.0);
            map.insert(TraitKey::Sociality, 95.0);
            map.insert(TraitKey::Order, 55.0);
            map.insert(TraitKey::Appetite, 40.0);
            map.insert(TraitKey::Caution, 55.0);
            map.insert(TraitKey::Curiosity, 50.0);
        }
        "greedy" => {
            map.insert(TraitKey::Vitality, 70.0);
            map.insert(TraitKey::Sociality, 30.0);
            map.insert(TraitKey::Order, 55.0);
            map.insert(TraitKey::Appetite, 85.0);
            map.insert(TraitKey::Caution, 35.0);
            map.insert(TraitKey::Curiosity, 60.0);
        }
        "melancholic" => {
            map.insert(TraitKey::Vitality, 20.0);
            map.insert(TraitKey::Sociality, 55.0);
            map.insert(TraitKey::Order, 60.0);
            map.insert(TraitKey::Appetite, 35.0);
            map.insert(TraitKey::Caution, 60.0);
            map.insert(TraitKey::Curiosity, 65.0);
        }
        "chaotic" => {
            map.insert(TraitKey::Vitality, 70.0);
            map.insert(TraitKey::Sociality, 40.0);
            map.insert(TraitKey::Order, 5.0);
            map.insert(TraitKey::Appetite, 50.0);
            map.insert(TraitKey::Caution, 20.0);
            map.insert(TraitKey::Curiosity, 80.0);
        }
        "stoic" => {
            map.insert(TraitKey::Vitality, 15.0);
            map.insert(TraitKey::Sociality, 35.0);
            map.insert(TraitKey::Order, 95.0);
            map.insert(TraitKey::Appetite, 20.0);
            map.insert(TraitKey::Caution, 30.0);
            map.insert(TraitKey::Curiosity, 20.0);
        }
        "adventurer" => {
            map.insert(TraitKey::Vitality, 75.0);
            map.insert(TraitKey::Sociality, 55.0);
            map.insert(TraitKey::Order, 25.0);
            map.insert(TraitKey::Appetite, 45.0);
            map.insert(TraitKey::Caution, 10.0);
            map.insert(TraitKey::Curiosity, 95.0);
        }
        "paranoid" => {
            map.insert(TraitKey::Vitality, 40.0);
            map.insert(TraitKey::Sociality, 20.0);
            map.insert(TraitKey::Order, 65.0);
            map.insert(TraitKey::Appetite, 35.0);
            map.insert(TraitKey::Caution, 95.0);
            map.insert(TraitKey::Curiosity, 55.0);
        }
        "curious" => {
            map.insert(TraitKey::Vitality, 65.0);
            map.insert(TraitKey::Sociality, 45.0);
            map.insert(TraitKey::Order, 60.0);
            map.insert(TraitKey::Appetite, 30.0);
            map.insert(TraitKey::Caution, 55.0);
            map.insert(TraitKey::Curiosity, 95.0);
        }
        _ => {
            for &key in TraitKey::all() {
                map.insert(key, 50.0);
            }
        }
    }
    map
}

pub fn personality_radius_base(id: &str) -> f64 {
    match id {
        "playful" => 25.0,
        "drowsy" => 25.0,
        "foodie" => 25.0,
        "bold" => 22.0,
        "zen" => 22.0,
        "anxious" => 22.0,
        "feral" => 20.0,
        "sage" => 22.0,
        "pristine" => 22.0,
        "empath" => 20.0,
        "greedy" => 20.0,
        "melancholic" => 22.0,
        "chaotic" => 20.0,
        "stoic" => 22.0,
        "adventurer" => 20.0,
        "paranoid" => 18.0,
        "curious" => 22.0,
        _ => 22.0,
    }
}

pub fn behavior_evidence_for_personality(
    axes: &HashMap<BehaviorAxis, f64>,
    personality_id: &str,
) -> f64 {
    let axis = |key: BehaviorAxis| axes.get(&key).copied().unwrap_or(0.0);

    match personality_id {
        "playful" => axis(BehaviorAxis::Play) * 1.0 + axis(BehaviorAxis::Exploration) * 0.4,
        "drowsy" => {
            axis(BehaviorAxis::Disruption) * 1.0 + (25.0 - axis(BehaviorAxis::Play)).max(0.0) * 0.5
        }
        "foodie" => axis(BehaviorAxis::Care) * 1.0 + axis(BehaviorAxis::Social) * 0.25,
        "bold" => {
            axis(BehaviorAxis::Play) * 1.0
                + axis(BehaviorAxis::Exploration) * 0.6
                + axis(BehaviorAxis::Disruption) * 0.2
        }
        "zen" => {
            axis(BehaviorAxis::Order) * 1.0
                + axis(BehaviorAxis::Care) * 0.5
                + axis(BehaviorAxis::Disruption) * -0.6
        }
        "anxious" => axis(BehaviorAxis::Disruption) * 1.0 + axis(BehaviorAxis::Recovery) * 0.5,
        "feral" => {
            axis(BehaviorAxis::Play) * 1.0
                + axis(BehaviorAxis::Disruption) * 0.8
                + (30.0 - axis(BehaviorAxis::Social)).max(0.0) * 0.3
        }
        "sage" => {
            axis(BehaviorAxis::Exploration) * 1.0
                + axis(BehaviorAxis::Order) * 0.7
                + axis(BehaviorAxis::Social) * 0.3
        }
        "pristine" => axis(BehaviorAxis::Order) * 1.0 + axis(BehaviorAxis::Care) * 0.4,
        "empath" => {
            axis(BehaviorAxis::Social) * 1.0
                + axis(BehaviorAxis::Care) * 0.5
                + axis(BehaviorAxis::Recovery) * 0.3
        }
        "greedy" => axis(BehaviorAxis::Care) * 1.0 + axis(BehaviorAxis::Exploration) * 0.5,
        "melancholic" => axis(BehaviorAxis::Disruption) * 1.0 + axis(BehaviorAxis::Social) * 0.2,
        "chaotic" => {
            axis(BehaviorAxis::Disruption) * 1.0
                + axis(BehaviorAxis::Play) * 0.7
                + axis(BehaviorAxis::Exploration) * 0.7
        }
        "stoic" => {
            axis(BehaviorAxis::Order) * 1.0 + (25.0 - axis(BehaviorAxis::Social)).max(0.0) * 0.4
        }
        "adventurer" => {
            axis(BehaviorAxis::Exploration) * 1.0
                + axis(BehaviorAxis::Play) * 0.6
                + axis(BehaviorAxis::Care) * 0.2
        }
        "paranoid" => axis(BehaviorAxis::Disruption) * 1.0 + axis(BehaviorAxis::Order) * 0.4,
        "curious" => {
            axis(BehaviorAxis::Exploration) * 1.0
                + axis(BehaviorAxis::Order) * 0.45
                + axis(BehaviorAxis::Social) * 0.25
                + axis(BehaviorAxis::Disruption) * -0.3
        }
        _ => 0.0,
    }
}
